// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TaskerClient is the client API for Tasker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskerClient interface {
	// Ping pongs.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// GetTask returns a specific task by ID. Status 5 "NOT_FOUND" is
	// reported if no task was found by that ID.
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	// GetActiveTask returns the currently active task (a task with no end time).
	// If no such task exists, then an empty reposne it returned instead.
	GetActiveTask(ctx context.Context, in *GetActiveTaskRequest, opts ...grpc.CallOption) (*GetActiveTaskResponse, error)
	// GetTaskList queries for a list of tasks.
	GetTaskList(ctx context.Context, in *GetTaskListRequest, opts ...grpc.CallOption) (*GetTaskListResponse, error)
	// CreateTask creates a new task and stops any currently active tasks, and
	// returns the stopped previously active task (if any) and the newly created
	// task.
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
	// UpdateTask alters a task by ID and returns the task's before and after
	// state. Status 5 "NOT_FOUND" is reported if no task was found by that ID.
	UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error)
	// DeleteTask removes a task by ID. Status 5 "NOT_FOUND" is=
	// reported if no task was found by that ID.
	DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskResponse, error)
	// StopActiveTask stops the currently active task and returns that task
	// (if any).
	StopActiveTask(ctx context.Context, in *StopActiveTaskRequest, opts ...grpc.CallOption) (*StopActiveTaskResponse, error)
	// StreamAlert streams task change events: created, updated, deleted.
	StreamTask(ctx context.Context, in *StreamTaskRequest, opts ...grpc.CallOption) (Tasker_StreamTaskClient, error)
}

type taskerClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskerClient(cc grpc.ClientConnInterface) TaskerClient {
	return &taskerClient{cc}
}

func (c *taskerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/dinkurapi.v1.Tasker/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskerClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, "/dinkurapi.v1.Tasker/GetTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskerClient) GetActiveTask(ctx context.Context, in *GetActiveTaskRequest, opts ...grpc.CallOption) (*GetActiveTaskResponse, error) {
	out := new(GetActiveTaskResponse)
	err := c.cc.Invoke(ctx, "/dinkurapi.v1.Tasker/GetActiveTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskerClient) GetTaskList(ctx context.Context, in *GetTaskListRequest, opts ...grpc.CallOption) (*GetTaskListResponse, error) {
	out := new(GetTaskListResponse)
	err := c.cc.Invoke(ctx, "/dinkurapi.v1.Tasker/GetTaskList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskerClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	out := new(CreateTaskResponse)
	err := c.cc.Invoke(ctx, "/dinkurapi.v1.Tasker/CreateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskerClient) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error) {
	out := new(UpdateTaskResponse)
	err := c.cc.Invoke(ctx, "/dinkurapi.v1.Tasker/UpdateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskerClient) DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskResponse, error) {
	out := new(DeleteTaskResponse)
	err := c.cc.Invoke(ctx, "/dinkurapi.v1.Tasker/DeleteTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskerClient) StopActiveTask(ctx context.Context, in *StopActiveTaskRequest, opts ...grpc.CallOption) (*StopActiveTaskResponse, error) {
	out := new(StopActiveTaskResponse)
	err := c.cc.Invoke(ctx, "/dinkurapi.v1.Tasker/StopActiveTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskerClient) StreamTask(ctx context.Context, in *StreamTaskRequest, opts ...grpc.CallOption) (Tasker_StreamTaskClient, error) {
	stream, err := c.cc.NewStream(ctx, &Tasker_ServiceDesc.Streams[0], "/dinkurapi.v1.Tasker/StreamTask", opts...)
	if err != nil {
		return nil, err
	}
	x := &taskerStreamTaskClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Tasker_StreamTaskClient interface {
	Recv() (*StreamTaskResponse, error)
	grpc.ClientStream
}

type taskerStreamTaskClient struct {
	grpc.ClientStream
}

func (x *taskerStreamTaskClient) Recv() (*StreamTaskResponse, error) {
	m := new(StreamTaskResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TaskerServer is the server API for Tasker service.
// All implementations must embed UnimplementedTaskerServer
// for forward compatibility
type TaskerServer interface {
	// Ping pongs.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// GetTask returns a specific task by ID. Status 5 "NOT_FOUND" is
	// reported if no task was found by that ID.
	GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	// GetActiveTask returns the currently active task (a task with no end time).
	// If no such task exists, then an empty reposne it returned instead.
	GetActiveTask(context.Context, *GetActiveTaskRequest) (*GetActiveTaskResponse, error)
	// GetTaskList queries for a list of tasks.
	GetTaskList(context.Context, *GetTaskListRequest) (*GetTaskListResponse, error)
	// CreateTask creates a new task and stops any currently active tasks, and
	// returns the stopped previously active task (if any) and the newly created
	// task.
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
	// UpdateTask alters a task by ID and returns the task's before and after
	// state. Status 5 "NOT_FOUND" is reported if no task was found by that ID.
	UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskResponse, error)
	// DeleteTask removes a task by ID. Status 5 "NOT_FOUND" is=
	// reported if no task was found by that ID.
	DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskResponse, error)
	// StopActiveTask stops the currently active task and returns that task
	// (if any).
	StopActiveTask(context.Context, *StopActiveTaskRequest) (*StopActiveTaskResponse, error)
	// StreamAlert streams task change events: created, updated, deleted.
	StreamTask(*StreamTaskRequest, Tasker_StreamTaskServer) error
	mustEmbedUnimplementedTaskerServer()
}

// UnimplementedTaskerServer must be embedded to have forward compatible implementations.
type UnimplementedTaskerServer struct {
}

func (UnimplementedTaskerServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedTaskerServer) GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTaskerServer) GetActiveTask(context.Context, *GetActiveTaskRequest) (*GetActiveTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveTask not implemented")
}
func (UnimplementedTaskerServer) GetTaskList(context.Context, *GetTaskListRequest) (*GetTaskListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskList not implemented")
}
func (UnimplementedTaskerServer) CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedTaskerServer) UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTask not implemented")
}
func (UnimplementedTaskerServer) DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedTaskerServer) StopActiveTask(context.Context, *StopActiveTaskRequest) (*StopActiveTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopActiveTask not implemented")
}
func (UnimplementedTaskerServer) StreamTask(*StreamTaskRequest, Tasker_StreamTaskServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamTask not implemented")
}
func (UnimplementedTaskerServer) mustEmbedUnimplementedTaskerServer() {}

// UnsafeTaskerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskerServer will
// result in compilation errors.
type UnsafeTaskerServer interface {
	mustEmbedUnimplementedTaskerServer()
}

func RegisterTaskerServer(s grpc.ServiceRegistrar, srv TaskerServer) {
	s.RegisterService(&Tasker_ServiceDesc, srv)
}

func _Tasker_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dinkurapi.v1.Tasker/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tasker_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskerServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dinkurapi.v1.Tasker/GetTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskerServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tasker_GetActiveTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskerServer).GetActiveTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dinkurapi.v1.Tasker/GetActiveTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskerServer).GetActiveTask(ctx, req.(*GetActiveTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tasker_GetTaskList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskerServer).GetTaskList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dinkurapi.v1.Tasker/GetTaskList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskerServer).GetTaskList(ctx, req.(*GetTaskListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tasker_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskerServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dinkurapi.v1.Tasker/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskerServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tasker_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskerServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dinkurapi.v1.Tasker/UpdateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskerServer).UpdateTask(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tasker_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskerServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dinkurapi.v1.Tasker/DeleteTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskerServer).DeleteTask(ctx, req.(*DeleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tasker_StopActiveTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopActiveTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskerServer).StopActiveTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dinkurapi.v1.Tasker/StopActiveTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskerServer).StopActiveTask(ctx, req.(*StopActiveTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tasker_StreamTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskerServer).StreamTask(m, &taskerStreamTaskServer{stream})
}

type Tasker_StreamTaskServer interface {
	Send(*StreamTaskResponse) error
	grpc.ServerStream
}

type taskerStreamTaskServer struct {
	grpc.ServerStream
}

func (x *taskerStreamTaskServer) Send(m *StreamTaskResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Tasker_ServiceDesc is the grpc.ServiceDesc for Tasker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tasker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dinkurapi.v1.Tasker",
	HandlerType: (*TaskerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Tasker_Ping_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _Tasker_GetTask_Handler,
		},
		{
			MethodName: "GetActiveTask",
			Handler:    _Tasker_GetActiveTask_Handler,
		},
		{
			MethodName: "GetTaskList",
			Handler:    _Tasker_GetTaskList_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _Tasker_CreateTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _Tasker_UpdateTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _Tasker_DeleteTask_Handler,
		},
		{
			MethodName: "StopActiveTask",
			Handler:    _Tasker_StopActiveTask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTask",
			Handler:       _Tasker_StreamTask_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/dinkurapi/v1/tasker.proto",
}
